#!/bin/sh
# DJAEGER AI Recovery Decision Engine
# Converts constrained AI recommendations into typed broker requests.
DECISION_STATE=/tmp/djaeger-modem/decision.state
DECISION_LEDGER=/root/djaeger-modem/decision-ledger.csv
safe_action(){ case "$1" in NONE|WAN_RECONNECT|NETIFD_RESTART|DNSMASQ_RESTART|MODEM_REBOOT) printf '%s' "$1";; *) printf NONE;; esac; }
safe_conf(){ case "$1" in ''|*[!0-9]*) echo 0;; *) [ "$1" -gt 100 ] && echo 100 || echo "$1";; esac; }
decision_local(){ case "${ROOT_DOMAIN:-UNKNOWN}" in OPENWRT_DNS|DNS_UPSTREAM) echo DNSMASQ_RESTART;; OPENWRT_WAN|OPENWRT_ROUTING|MODEM_DATA_SESSION|UPSTREAM) echo WAN_RECONNECT;; OPENWRT_SYSTEM) echo NETIFD_RESTART;; CELLULAR|MODEM) echo WAN_RECONNECT;; MULTI_FACTOR) echo WAN_RECONNECT;; *) echo NONE;; esac; }
field(){ printf '%s' "$1" | tr ';' '\n' | sed -n "s/^$2=//p" | head -n1; }
state_field(){ sed -n "s/^$2=//p" "$1" 2>/dev/null | head -n1; }
decision_ledger_init(){ mkdir -p /root/djaeger-modem; [ -f "$DECISION_LEDGER" ] || printf 'epoch,source,action,confidence,state,root_domain,incident_start\n' > "$DECISION_LEDGER"; chmod 600 "$DECISION_LEDGER" 2>/dev/null; }
decision_ledger_append(){ decision_ledger_init; printf '%s,%s,%s,%s,%s,%s,%s\n' "$(date +%s)" "$1" "$2" "$3" "${CUR:-UNKNOWN}" "${ROOT_DOMAIN:-UNKNOWN}" "${INCIDENT_START:-0}" >> "$DECISION_LEDGER"; L="$(awk 'END{print NR+0}' "$DECISION_LEDGER" 2>/dev/null)"; [ "${L:-0}" -gt 2001 ] && { head -n1 "$DECISION_LEDGER" > "$DECISION_LEDGER.new"; tail -n 2000 "$DECISION_LEDGER" >> "$DECISION_LEDGER.new"; chmod 600 "$DECISION_LEDGER.new"; mv "$DECISION_LEDGER.new" "$DECISION_LEDGER"; }; }
decision_from_gemini(){ GS="${GEMINI_STATE:-/root/djaeger-modem/gemini/advisor.state}"; [ -f "$GS" ] || { echo NONE:0; return; }; S="$(state_field "$GS" status)"; [ "$S" = OK ] || { echo NONE:0; return; }; NOW="$(date +%s)"; UPD="$(state_field "$GS" updated)"; MAXAGE="$(uciopt gemini_action_max_age 180)"; case "$UPD:$MAXAGE" in *[!0-9:]*) echo NONE:0; return;; esac; [ "$MAXAGE" -gt 0 ] || { echo NONE:0; return; }; [ "$UPD" -le "$NOW" ] 2>/dev/null || { echo NONE:0; return; }; [ $((NOW-UPD)) -le "$MAXAGE" ] 2>/dev/null || { echo NONE:0; return; }; CS="$(state_field "$GS" context_state)"; CR="$(state_field "$GS" context_root_domain)"; CI="$(state_field "$GS" context_incident_start)"; case "${CUR:-STARTING}" in OUTAGE|RECOVERING) :;; *) echo NONE:0; return;; esac; case "$CS" in OUTAGE|RECOVERING) :;; *) echo NONE:0; return;; esac; [ "$CR" = "${ROOT_DOMAIN:-UNKNOWN}" ] || { echo NONE:0; return; }; case "$CI:${INCIDENT_START:-0}" in *[!0-9:]*) echo NONE:0; return;; esac; [ "$CI" -gt 0 ] 2>/dev/null && [ "$CI" = "${INCIDENT_START:-0}" ] || { echo NONE:0; return; }; T="$(state_field "$GS" advice)"; A="$(field "$T" ACTION)"; C="$(field "$T" ACTION_CONFIDENCE)"; [ -n "$C" ] || C="$(field "$T" CONFIDENCE)"; A="$(safe_action "$A")"; C="$(safe_conf "$C")"; echo "$A:$C"; }
decision_choose(){ LOCAL="$(safe_action "$(decision_local)")"; CHOSEN="$LOCAL"; SOURCE=LOCAL; CONF="${ROOT_CONF:-0}"; G="$(decision_from_gemini)"; GA="${G%%:*}"; GC="${G#*:}"; MIN="$(uciopt ai_action_min_confidence 80)"; case "$MIN" in ''|*[!0-9]*) MIN=80;; esac; if [ "$GA" != NONE ] && [ "$GC" -ge "$MIN" ] 2>/dev/null && broker_action_allowed "$GA" && broker_domain_allows "$GA"; then CHOSEN="$GA"; SOURCE=GEMINI_VALIDATED; CONF="$GC"; fi; CONF="$(safe_conf "$CONF")"; mkdir -p /tmp/djaeger-modem; printf 'source=%s\naction=%s\nconfidence=%s\nroot_domain=%s\nincident_start=%s\nepoch=%s\n' "$SOURCE" "$CHOSEN" "$CONF" "${ROOT_DOMAIN:-UNKNOWN}" "${INCIDENT_START:-0}" "$(date +%s)" > "$DECISION_STATE.tmp"; chmod 600 "$DECISION_STATE.tmp"; mv "$DECISION_STATE.tmp" "$DECISION_STATE"; decision_ledger_append "$SOURCE" "$CHOSEN" "$CONF"; printf '%s:%s:%s\n' "$SOURCE" "$CHOSEN" "$CONF"; }
decision_execute_selected(){ SRC="$1"; ACT="$(safe_action "$2")"; CONF="$(safe_conf "$3")"; [ "$ACT" != NONE ] || return 1; MIN="$(uciopt ai_action_min_confidence 80)"; case "$MIN" in ''|*[!0-9]*) MIN=80;; esac; [ "$CONF" -ge "$MIN" ] 2>/dev/null || return 1; broker_execute "$SRC" "$ACT"; }
decision_execute(){ D="$(decision_choose)"; SRC="${D%%:*}"; R="${D#*:}"; ACT="${R%%:*}"; CONF="${R#*:}"; decision_execute_selected "$SRC" "$ACT" "$CONF"; }
