#!/bin/sh
# DJAEGER AI Recovery Decision Engine
# Converts constrained AI recommendations into typed broker requests.
DECISION_STATE=/tmp/djaeger-modem/decision.state
safe_action(){ case "$1" in NONE|WAN_RECONNECT|NETIFD_RESTART|DNSMASQ_RESTART|MODEM_REBOOT) printf '%s' "$1";; *) printf NONE;; esac; }
safe_conf(){ case "$1" in ''|*[!0-9]*) echo 0;; *) [ "$1" -gt 100 ] && echo 100 || echo "$1";; esac; }
decision_local(){ case "${ROOT_DOMAIN:-UNKNOWN}" in OPENWRT_DNS|DNS_UPSTREAM) echo DNSMASQ_RESTART;; OPENWRT_WAN|OPENWRT_ROUTING|MODEM_DATA_SESSION|UPSTREAM) echo WAN_RECONNECT;; OPENWRT_SYSTEM) echo NETIFD_RESTART;; CELLULAR|MODEM) echo WAN_RECONNECT;; MULTI_FACTOR) echo WAN_RECONNECT;; *) echo NONE;; esac; }
decision_from_gemini(){ [ -f "${GEMINI_STATE:-/root/djaeger-modem/gemini/advisor.state}" ] || { echo NONE:0; return; }; S="$(sed -n 's/^status=//p' "$GEMINI_STATE" 2>/dev/null | head -n1)"; [ "$S" = OK ] || { echo NONE:0; return; }; T="$(sed -n 's/^advice=//p' "$GEMINI_STATE" 2>/dev/null | head -n1 | tr '_' ' ')"; A="$(printf '%s' "$T" | sed -n 's/.*ACTION=\([A-Z_]*\).*/\1/p' | head -n1)"; C="$(printf '%s' "$T" | sed -n 's/.*CONFIDENCE=\([0-9][0-9]*\).*/\1/p' | head -n1)"; A="$(safe_action "$A")"; C="$(safe_conf "$C")"; echo "$A:$C"; }
decision_choose(){ LOCAL="$(safe_action "$(decision_local)")"; CHOSEN="$LOCAL"; SOURCE=LOCAL; CONF="${ROOT_CONFIDENCE:-0}"; G="$(decision_from_gemini)"; GA="${G%%:*}"; GC="${G#*:}"; MIN="$(uciopt ai_action_min_confidence 80)"; case "$MIN" in ''|*[!0-9]*) MIN=80;; esac; if [ "$GA" != NONE ] && [ "$GC" -ge "$MIN" ] 2>/dev/null && broker_action_allowed "$GA" && broker_domain_allows "$GA"; then CHOSEN="$GA"; SOURCE=GEMINI_VALIDATED; CONF="$GC"; fi; case "$CONF" in ''|*[!0-9]*) CONF=0;; esac; printf 'source=%s\naction=%s\nconfidence=%s\nroot_domain=%s\nepoch=%s\n' "$SOURCE" "$CHOSEN" "$CONF" "${ROOT_DOMAIN:-UNKNOWN}" "$(date +%s)" > "$DECISION_STATE.tmp"; chmod 600 "$DECISION_STATE.tmp"; mv "$DECISION_STATE.tmp" "$DECISION_STATE"; printf '%s:%s:%s\n' "$SOURCE" "$CHOSEN" "$CONF"; }
decision_execute(){ D="$(decision_choose)"; SRC="${D%%:*}"; R="${D#*:}"; ACT="${R%%:*}"; CONF="${R#*:}"; [ "$ACT" != NONE ] || return 1; MIN="$(uciopt ai_action_min_confidence 80)"; case "$MIN" in ''|*[!0-9]*) MIN=80;; esac; [ "$CONF" -ge "$MIN" ] 2>/dev/null || return 1; broker_execute "$SRC" "$ACT"; }
