#!/bin/sh
# DJAEGER Autonomous Root Recovery Broker
# Root authority is capability-based: no eval, no sh -c, no model-supplied command/path/url/body.
BROKER_LOG=/root/djaeger-modem/root-broker.csv
[ -f "$BROKER_LOG" ] || echo 'epoch,source,domain,action,result,verification' > "$BROKER_LOG"
broker_log(){ printf '%s,%s,%s,%s,%s,%s\n' "$(date +%s)" "$1" "${ROOT_DOMAIN:-UNKNOWN}" "$2" "$3" "$4" >> "$BROKER_LOG"; L="$(wc -l < "$BROKER_LOG" 2>/dev/null)"; [ "${L:-0}" -gt 1001 ] && { head -n1 "$BROKER_LOG" > "$BROKER_LOG.new"; tail -n 1000 "$BROKER_LOG" >> "$BROKER_LOG.new"; mv "$BROKER_LOG.new" "$BROKER_LOG"; }; }
broker_verify(){ ping -c 1 -W 3 "${GW:-192.168.8.1}" >/dev/null 2>&1 || return 1; ping -c 1 -W 3 1.1.1.1 >/dev/null 2>&1 || ping -c 1 -W 3 8.8.8.8 >/dev/null 2>&1 || return 1; nslookup example.com 127.0.0.1 >/dev/null 2>&1 || nslookup example.com >/dev/null 2>&1 || return 1; return 0; }
broker_action_allowed(){ case "$1" in WAN_RECONNECT|NETIFD_RESTART|DNSMASQ_RESTART|MODEM_REBOOT) return 0;; *) return 1;; esac; }
broker_domain_allows(){ A="$1"; case "$A" in WAN_RECONNECT) case "${ROOT_DOMAIN:-UNKNOWN}" in OPENWRT_WAN|OPENWRT_ROUTING|MODEM_DATA_SESSION|CELLULAR|MODEM|MULTI_FACTOR|UPSTREAM) return 0;; esac;; NETIFD_RESTART) case "${ROOT_DOMAIN:-UNKNOWN}" in OPENWRT_WAN|OPENWRT_ROUTING|OPENWRT_SYSTEM|MULTI_FACTOR) return 0;; esac;; DNSMASQ_RESTART) case "${ROOT_DOMAIN:-UNKNOWN}" in OPENWRT_DNS|DNS_UPSTREAM|OPENWRT_SYSTEM|MULTI_FACTOR) return 0;; esac;; MODEM_REBOOT) case "${ROOT_DOMAIN:-UNKNOWN}" in CELLULAR|MODEM|MODEM_DATA_SESSION|MULTI_FACTOR) return 0;; esac;; esac; return 1; }
broker_execute(){ SRC="$1"; ACT="$2"; broker_action_allowed "$ACT" || { broker_log "$SRC" "$ACT" REJECTED ACTION_NOT_ALLOWLISTED; return 1; }; broker_domain_allows "$ACT" || { broker_log "$SRC" "$ACT" REJECTED DOMAIN_MISMATCH; return 1; }; [ "${CUR:-STARTING}" = OUTAGE ] || [ "${CUR:-STARTING}" = RECOVERING ] || { broker_log "$SRC" "$ACT" REJECTED NOT_CONFIRMED_OUTAGE; return 1; }; case "$ACT" in WAN_RECONNECT) [ "$(uciopt allow_wan_reconnect 0)" = 1 ] || { broker_log "$SRC" "$ACT" LOCKED POLICY; return 1; }; ifup wan >/dev/null 2>&1 || { broker_log "$SRC" "$ACT" FAILED EXECUTION; return 1; };; NETIFD_RESTART) [ "$(uciopt allow_service_recovery 0)" = 1 ] || { broker_log "$SRC" "$ACT" LOCKED POLICY; return 1; }; /etc/init.d/network restart >/dev/null 2>&1 || { broker_log "$SRC" "$ACT" FAILED EXECUTION; return 1; };; DNSMASQ_RESTART) [ "$(uciopt allow_service_recovery 0)" = 1 ] || { broker_log "$SRC" "$ACT" LOCKED POLICY; return 1; }; /etc/init.d/dnsmasq restart >/dev/null 2>&1 || { broker_log "$SRC" "$ACT" FAILED EXECUTION; return 1; };; MODEM_REBOOT) [ "$(uciopt allow_modem_post 0)" = 1 ] && [ "$(uciopt allow_modem_reboot 0)" = 1 ] || { broker_log "$SRC" "$ACT" LOCKED POLICY; return 1; }; recover_modem_reboot || { broker_log "$SRC" "$ACT" FAILED EXECUTION; return 1; };; esac; broker_log "$SRC" "$ACT" STARTED PENDING_VERIFICATION; return 0; }
broker_verify_result(){ SRC="$1"; ACT="$2"; if broker_verify; then broker_log "$SRC" "$ACT" SUCCESS INTERNET_OK; return 0; fi; broker_log "$SRC" "$ACT" FAILED VERIFICATION; return 1; }
