#!/bin/sh
# DJAEGER evidence-based Root Cause Correlation Engine
rootcause_correlate(){
 ROOT_DOMAIN=UNKNOWN; ROOT_REASON="$CAUSE"; ROOT_CONF="$CONF"
 case "$CAUSE" in
  CELLULAR_SERVICE_LOST|MODEM_PRESENT_BUT_NO_NETWORK|RADIO_DEGRADED) ROOT_DOMAIN=CELLULAR;;
  SIM_OR_MODEM_SERVICE|MODEM_UNREACHABLE) ROOT_DOMAIN=MODEM;;
  MODEM_PATH_FAILURE) if [ "${USB_PRESENT:-1}" = 0 ]; then ROOT_DOMAIN=USB_MODEM_PATH; ROOT_CONF=88; elif [ "${KERR:-0}" -ge 3 ] 2>/dev/null; then ROOT_DOMAIN=USB_MODEM_PATH; ROOT_CONF=78; else ROOT_DOMAIN=MODEM_PATH; fi;;
  DATA_SESSION_LOST) if [ "${WAN_UP:-1}" = 0 ]; then ROOT_DOMAIN=OPENWRT_WAN; elif [ "${ROUTE_OK:-1}" = 0 ]; then ROOT_DOMAIN=OPENWRT_ROUTING; else ROOT_DOMAIN=MODEM_DATA_SESSION; fi;;
  DNS_FAILURE) if [ "${DNSMASQ_OK:-1}" = 0 ]; then ROOT_DOMAIN=OPENWRT_DNS; else ROOT_DOMAIN=DNS_UPSTREAM; fi;;
  UPSTREAM_OR_DATA_SESSION) if [ "${WAN_UP:-1}" = 0 ]; then ROOT_DOMAIN=OPENWRT_WAN; elif [ "${ROUTE_OK:-1}" = 0 ]; then ROOT_DOMAIN=OPENWRT_ROUTING; elif [ "${CTPCT:-0}" -ge 90 ] 2>/dev/null || [ "${MEMPCT:-100}" -le 8 ] 2>/dev/null; then ROOT_DOMAIN=OPENWRT_RESOURCE_PRESSURE; else ROOT_DOMAIN=UPSTREAM; fi;;
  NONE) if [ "${SYS_RISK:-0}" -ge 50 ] 2>/dev/null; then ROOT_DOMAIN=OPENWRT_PREFAILURE; ROOT_REASON="${SYS_REASON:-SYSTEM_ANOMALY}"; ROOT_CONF=72; else ROOT_DOMAIN=HEALTHY; ROOT_REASON=NORMAL; ROOT_CONF=95; fi;;
 esac
 # Strong explicit cellular/modem evidence remains primary. Concurrent severe OpenWrt evidence becomes multi-factor, not an override.
 if [ "${SYS_RISK:-0}" -ge 70 ] 2>/dev/null; then case "$ROOT_DOMAIN" in CELLULAR|MODEM|MODEM_DATA_SESSION|MODEM_PATH|USB_MODEM_PATH) ROOT_DOMAIN=MULTI_FACTOR; ROOT_REASON="${CAUSE}+${SYS_REASON:-OPENWRT_ANOMALY}"; [ "$ROOT_CONF" -lt 85 ] 2>/dev/null && ROOT_CONF=85;; OPENWRT_*) :;; *) ROOT_DOMAIN=OPENWRT_SYSTEM; ROOT_REASON="${SYS_REASON:-SYSTEM_ANOMALY}"; [ "$ROOT_CONF" -lt 82 ] 2>/dev/null && ROOT_CONF=82;; esac; fi
}
