#!/bin/sh
# DJAEGER Root Cause Correlation Engine
rootcause_correlate(){
 ROOT_DOMAIN=UNKNOWN; ROOT_REASON="$CAUSE"; ROOT_CONF="$CONF"
 case "$CAUSE" in
  CELLULAR_SERVICE_LOST|RADIO_DEGRADED) ROOT_DOMAIN=CELLULAR;;
  SIM_OR_MODEM_SERVICE|MODEM_UNREACHABLE) ROOT_DOMAIN=MODEM;;
  MODEM_PATH_FAILURE) [ "${USB_PRESENT:-1}" = 0 ] || [ "${KERR:-0}" -ge 3 ] 2>/dev/null && ROOT_DOMAIN=OPENWRT_USB_KERNEL || ROOT_DOMAIN=MODEM_PATH;;
  DATA_SESSION_LOST) if [ "${WAN_UP:-1}" = 0 ] || [ "${ROUTE_OK:-1}" = 0 ]; then ROOT_DOMAIN=OPENWRT_WAN; else ROOT_DOMAIN=MODEM_DATA_SESSION; fi;;
  DNS_FAILURE) [ "${DNSMASQ_OK:-1}" = 0 ] && ROOT_DOMAIN=OPENWRT_DNS || ROOT_DOMAIN=DNS_UPSTREAM;;
  UPSTREAM_OR_DATA_SESSION) if [ "${WAN_UP:-1}" = 0 ] || [ "${ROUTE_OK:-1}" = 0 ]; then ROOT_DOMAIN=OPENWRT_WAN; elif [ "${CTPCT:-0}" -ge 90 ] 2>/dev/null; then ROOT_DOMAIN=OPENWRT_RESOURCE; else ROOT_DOMAIN=UPSTREAM_OR_MODEM; fi;;
  NONE) if [ "${SYS_RISK:-0}" -ge 50 ] 2>/dev/null; then ROOT_DOMAIN=OPENWRT_PREFAILURE; ROOT_REASON="${SYS_REASON:-SYSTEM_ANOMALY}"; ROOT_CONF=75; else ROOT_DOMAIN=HEALTHY; ROOT_REASON=NORMAL; ROOT_CONF=95; fi;;
 esac
 [ "${SYS_RISK:-0}" -ge 70 ] 2>/dev/null && case "$ROOT_DOMAIN" in CELLULAR|MODEM) :;; *) ROOT_DOMAIN=OPENWRT_SYSTEM; ROOT_REASON="${SYS_REASON:-SYSTEM_ANOMALY}"; [ "$ROOT_CONF" -lt 85 ] 2>/dev/null && ROOT_CONF=85;; esac
}
