#!/bin/sh
# DJAEGER Autonomous Root Recovery Broker v4
umask 077
BROKER_BASE=/root/djaeger-modem;BROKER_LOG=$BROKER_BASE/root-broker.csv;mkdir -p "$BROKER_BASE";[ -f "$BROKER_LOG" ]||echo 'epoch,source,domain,action,result,verification' >"$BROKER_LOG";chmod 600 "$BROKER_LOG" 2>/dev/null
broker_log(){ printf '%s,%s,%s,%s,%s,%s\n' "$(date +%s)" "$1" "${ROOT_DOMAIN:-UNKNOWN}" "$2" "$3" "$4">>"$BROKER_LOG"; };broker_last(){ awk -F, -v a="$1" '$4==a&&($5=="STARTED"||$5=="SUCCESS"){x=$1}END{print x+0}' "$BROKER_LOG" 2>/dev/null; };broker_count_hour(){ N="$(date +%s)";awk -F, -v a="$1" -v n="$N" '$4==a&&($5=="STARTED"||$5=="SUCCESS")&&$1>=n-3600{c++}END{print c+0}' "$BROKER_LOG" 2>/dev/null; }
broker_budget(){ A="$1";NOW="$(date +%s)";LAST="$(broker_last "$A")";CNT="$(broker_count_hour "$A")";case "$A" in WAN_RECONNECT)CD="$(uciopt broker_wan_cooldown 30)";MAX="$(uciopt broker_wan_max_hour 6)";;DNSMASQ_RESTART)CD="$(uciopt broker_dns_cooldown 120)";MAX="$(uciopt broker_dns_max_hour 3)";;NETIFD_RESTART)CD="$(uciopt broker_netifd_cooldown 120)";MAX="$(uciopt broker_netifd_max_hour 3)";;MODEM_REBOOT)CD="$(uciopt modem_reboot_cooldown 120)";MAX="$(uciopt max_modem_reboots_hour 3)";;*)return 1;;esac;case "$CD:$MAX" in *[!0-9:]*)return 1;;esac;[ "$MAX" -gt 0 ]||return 1;[ "$LAST" -gt 0 ]&&[ $((NOW-LAST)) -lt "$CD" ]&&return 1;[ "$CNT" -ge "$MAX" ]&&return 1; }
broker_action_allowed(){ case "$1" in WAN_RECONNECT|NETIFD_RESTART|DNSMASQ_RESTART|MODEM_REBOOT)return 0;;*)return 1;;esac; };broker_domain_allows(){ case "$1" in WAN_RECONNECT)case "${ROOT_DOMAIN:-UNKNOWN}" in OPENWRT_WAN|OPENWRT_ROUTING|MODEM_DATA_SESSION|REGISTERED_NO_DATA_SESSION|DATA_SESSION_STALLED|MULTI_FACTOR|UPSTREAM|UNKNOWN)return 0;;esac;;NETIFD_RESTART)case "${ROOT_DOMAIN:-UNKNOWN}" in OPENWRT_WAN|OPENWRT_ROUTING|OPENWRT_SYSTEM|MULTI_FACTOR|MODEM_DATA_SESSION|UNKNOWN)return 0;;esac;;DNSMASQ_RESTART)case "${ROOT_DOMAIN:-UNKNOWN}" in OPENWRT_DNS|DNS_UPSTREAM|OPENWRT_SYSTEM|MULTI_FACTOR)return 0;;esac;;MODEM_REBOOT)case "${ROOT_DOMAIN:-UNKNOWN}" in CELLULAR|MODEM|MODEM_PROVIDER|MODEM_DATA_SESSION|PLMN_VISIBLE_NOT_REGISTERED|REGISTRATION_STUCK|REGISTERED_NO_DATA_SESSION|DATA_SESSION_STALLED|RADIO_OR_PROVIDER_UNAVAILABLE|MODEM_API_UNAVAILABLE|SIM_OR_SERVICE_FAILURE|MULTI_FACTOR|UNKNOWN)return 0;;esac;;esac;return 1; }
service_present(){ ubus call service list "{\"name\":\"$1\"}" 2>/dev/null|grep -q "\"$1\""; }
broker_execute(){ SRC="$1";ACT="$2";broker_action_allowed "$ACT"||{ broker_log "$SRC" "$ACT" REJECTED ACTION_NOT_ALLOWLISTED;return 1; };broker_domain_allows "$ACT"||{ broker_log "$SRC" "$ACT" REJECTED DOMAIN_MISMATCH;return 1; };case "${CUR:-STARTING}" in OUTAGE|RECOVERING):;;*)broker_log "$SRC" "$ACT" REJECTED NOT_CONFIRMED_OUTAGE;return 1;;esac;broker_budget "$ACT"||{ broker_log "$SRC" "$ACT" REJECTED BUDGET_OR_COOLDOWN;return 1; }
 case "$ACT" in WAN_RECONNECT)[ "$(uciopt allow_wan_reconnect 0)" = 1 ]||{ broker_log "$SRC" "$ACT" LOCKED POLICY;return 1; };ifup wan >/dev/null 2>&1||{ broker_log "$SRC" "$ACT" FAILED EXECUTION;return 1; };broker_log "$SRC" "$ACT" STARTED PENDING_VERIFICATION;;DNSMASQ_RESTART)[ "$(uciopt allow_service_recovery 0)" = 1 ]&&[ "$(uciopt allow_dnsmasq_restart 0)" = 1 ]||{ broker_log "$SRC" "$ACT" LOCKED POLICY;return 1; };service_present dnsmasq||return 1;/etc/init.d/dnsmasq restart >/dev/null 2>&1||return 1;broker_log "$SRC" "$ACT" STARTED PENDING_VERIFICATION;;NETIFD_RESTART)[ "$(uciopt allow_service_recovery 0)" = 1 ]&&[ "$(uciopt allow_netifd_restart 0)" = 1 ]||{ broker_log "$SRC" "$ACT" LOCKED POLICY;return 1; };/etc/init.d/network restart >/dev/null 2>&1||return 1;broker_log "$SRC" "$ACT" STARTED PENDING_VERIFICATION;;MODEM_REBOOT)[ "$(uciopt allow_modem_post 0)" = 1 ]&&[ "$(uciopt allow_modem_reboot 0)" = 1 ]||{ broker_log "$SRC" "$ACT" LOCKED POLICY;return 1; };RECOVERY_EFFECT=NONE;if recover_modem_reboot;then if [ "${RECOVERY_EFFECT:-NONE}" = PASSIVE_RECOVERY ];then broker_log "$SRC" WAIT_API SUCCESS PASSIVE_RECOVERY_NO_REBOOT;else broker_log "$SRC" MODEM_REBOOT SUCCESS PHASE_VERIFIED_INTERNET_OK;fi;return 0;else broker_log "$SRC" MODEM_REBOOT FAILED PHASE_STATE_MACHINE_FAILED;return 1;fi;;esac; }
broker_verify_result(){ ping -c1 -W3 "${GW:-192.168.8.1}" >/dev/null 2>&1&&{ ping -c1 -W3 1.1.1.1 >/dev/null 2>&1||ping -c1 -W3 8.8.8.8 >/dev/null 2>&1; }&&{ broker_log "$1" "$2" SUCCESS INTERNET_OK;return 0; };broker_log "$1" "$2" FAILED VERIFICATION;return 1; }
