plugins {
    id 'com.android.application'
}

android {
    namespace 'com.djaeger.facebookadshield526'
    compileSdk 35

    defaultConfig {
        applicationId 'com.djaeger.facebookadshield526'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '0.3-shadow3'
    }

    signingConfigs {
        djaegerStable {
            storeFile rootProject.file('signing/djaeger-fb526-release.jks')
            storePassword 'djaeger526'
            keyAlias 'djaegerfb526'
            keyPassword 'djaeger526'
        }
    }

    buildTypes {
        debug {
            debuggable true
            signingConfig signingConfigs.djaegerStable
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly project(':xposed-stubs')
}
