plugins {
    id 'com.android.application'
}

android {
    namespace 'com.djaeger.facebookadshield526'
    compileSdk 35

    defaultConfig {
        applicationId 'com.djaeger.facebookadshield526'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1-shadow1'
    }

    buildTypes {
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly project(':xposed-stubs')
}
