#!/bin/sh /etc/rc.common
START=98
STOP=10
USE_PROCD=1
start_service(){
 [ "$(uci -q get djaeger_modem.main.enabled)" = 1 ] || return 0
 procd_open_instance
 procd_set_param command /usr/sbin/djaeger-modemd
 procd_set_param respawn 3600 5 5
 procd_set_param stdout 0
 procd_set_param stderr 1
 procd_close_instance
}
