#!/bin/sh /etc/rc.common
USE_PROCD=1
START=98
STOP=10
start_service(){ procd_open_instance; procd_set_param command /bin/sh -c 'while :; do /usr/lib/djaeger-modem/gemini-policy-learning.sh; sleep 30; done'; procd_set_param respawn 5 10 0; procd_close_instance; }
